# Use the official Nginx base image
FROM nginx

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Copy the contents of the local directory into the container
COPY app .
